version: 0.2

#env:
  #variables:
     # key: "value"
     # key: "value"
  #parameter-store:
     # key: "value"
     # key: "value"

phases:
  #install:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
  build:
    commands:
      - aws s3 cp index.html s3://www.jdawber.co.uk/index.html
      - aws s3 cp sitemap.xml s3://www.jdawber.co.uk/sitemap.xml
      # - command
    #finally:
      # - command
      # - command
  #post_build:
    #commands:
      # - command
      # - command
    #finally:
      # - command
      # - command
#artifacts:
  #files:
    # - location
    # - location
    # - name
  #discard-paths: yes
  #base-directory: location
#cache:
  #paths:
    # - path
    # - path